#lang s-exp "../rooms.rkt"
; North of display location
1 "progress bar"
(success (command (look (room (name "52nd Street and Dorchester Avenue")(description "You are standing at the corner of 52nd Street and Dorchester Avenue. From here, you can go east or south. ")(items ((item (name "V-5065-KLY")(description "an exemplary instance of part number V-5065-KLY")(adjectives ((adjective "cerise") ))(condition (broken (condition (broken (condition (pristine ))(missing ((kind (name "Z-6678-POH")(condition (pristine ))) ))))(missing ((kind (name "H-4832-ZUV")(condition (broken (condition (pristine ))(missing ((kind (name "L-1403-EXE")(condition (broken (condition (pristine ))(missing ((kind (name "P-0010-JBL")(condition (pristine ))) ))))) ))))) ))))(piled_on ((item (name "J-5065-IQW")(description "an exemplary instance of part number J-5065-IQW")(adjectives ((adjective "foreign") ))(condition (pristine ))(piled_on ((item (name "X-5065-GVU")(description "an exemplary instance of part number X-5065-GVU")(adjectives ((adjective "floating") ))(condition (pristine ))(piled_on ((item (name "B-6678-LYD")(description "an exemplary instance of part number B-6678-LYD")(adjectives ((adjective "chartreuse") ))(condition (pristine ))(piled_on ((item (name "N-1403-AIY")(description "an exemplary instance of part number N-1403-AIY")(adjectives ((adjective "lavender") ))(condition (pristine ))(piled_on ((item (name "R-0010-FLH")(description "an exemplary instance of part number R-0010-FLH")(adjectives ((adjective "bondi-blue") ))(condition (pristine ))(piled_on ((item (name "V-1623-KOO")(description "an exemplary instance of part number V-1623-KOO")(adjectives ((adjective "old") ))(condition (pristine ))(piled_on ((item (name "Z-1403-CDC")(description "an exemplary instance of part number Z-1403-CDC")(adjectives ((adjective "deep-sky-blue") ))(condition (broken (condition (broken (condition (pristine ))(missing ((kind (name "D-0010-HGJ")(condition (broken (condition (pristine ))(missing ((kind (name "H-1623-MJQ")(condition (pristine ))) ))))) ))))(missing ((kind (name "B-6678-LYD")(condition (pristine ))) ))))(piled_on ((item (name "B-9887-YKI")(description "an exemplary instance of part number B-9887-YKI")(adjectives ((adjective "hot-pink") ))(condition (pristine ))(piled_on ((item (name "P-9887-WPG")(description "an exemplary instance of part number P-9887-WPG")(adjectives ((adjective "ultramarine") ))(condition (broken (condition (pristine ))(missing ((kind (name "T-6458-BSN")(condition (pristine ))) ))))(piled_on ((item (name "F-9247-QCK")(description "an exemplary instance of part number F-9247-QCK")(adjectives ((adjective "fern-green") ))(condition (broken (condition (pristine ))(missing ((kind (name "J-4832-VFR")(condition (pristine ))) ))))(piled_on ((item (name "B-9247-YHS")(description "an exemplary instance of part number B-9247-YHS")(adjectives ((adjective "lime-green") ))(condition (broken (condition (pristine ))(missing ((kind (name "F-4832-DKZ")(condition (pristine ))) ))))(piled_on ((item (name "J-1403-INI")(description "an exemplary instance of part number J-1403-INI")(adjectives ((adjective "reverse-chirality") ))(condition (broken (condition (broken (condition (pristine ))(missing ((kind (name "N-0010-NQP")(condition (pristine ))) ))))(missing ((kind (name "X-4292-THZ")(condition (pristine ))) ))))(piled_on ((item (name "L-4292-RMX")(description "an exemplary instance of part number L-4292-RMX")(adjectives ((adjective "school-bus-yellow") ))(condition (pristine ))(piled_on ((item (name "R-6458-FIR")(description "an exemplary instance of part number R-6458-FIR")(adjectives ((adjective "yellow-green") ))(condition (broken (condition (broken (condition (pristine ))(missing ((kind (name "T-1623-OES")(condition (pristine ))) ))))(missing ((kind (name "L-4292-RMX")(condition (pristine ))) ))))(piled_on ((item (name "R-9247-SWM")(description "an exemplary instance of part number R-9247-SWM")(adjectives ((adjective "puce") ))(condition (broken (condition (pristine ))(missing ((kind (name "V-4832-XAT")(condition (pristine ))) ))))(piled_on ((item (name "V-4832-XAT")(description "an exemplary instance of part number V-4832-XAT")(adjectives ((adjective "carrot") ))(condition (pristine ))(piled_on ((item (name "H-4832-ZUV")(description "an exemplary instance of part number H-4832-ZUV")(adjectives ((adjective "discounted") ))(condition (broken (condition (pristine ))(missing ((kind (name "L-1403-EXE")(condition (broken (condition (pristine ))(missing ((kind (name "P-0010-JBL")(condition (pristine ))) ))))) ))))(piled_on ((item (name "N-6678-NTF")(description "an exemplary instance of part number N-6678-NTF")(adjectives ((adjective "hot-pink") ))(condition (pristine ))(piled_on ((item (name "L-6678-RJJ")(description "an exemplary instance of part number L-6678-RJJ")(adjectives ((adjective "exceptional") ))(condition (broken (condition (broken (condition (pristine ))(missing ((kind (name "P-9247-WMQ")(condition (broken (condition (pristine ))(missing ((kind (name "T-4832-BPX")(condition (pristine ))) ))))) ))))(missing ((kind (name "B-0010-LVN")(condition (broken (condition (pristine ))(missing ((kind (name "F-1623-QYU")(condition (broken (condition (broken (condition (pristine ))(missing ((kind (name "J-4292-VCD")(condition (pristine ))) ))))(missing ((kind (name "N-9887-AFK")(condition (pristine ))) ))))) ))))) ))))(piled_on ((item (name "F-6458-DNP")(description "an exemplary instance of part number F-6458-DNP")(adjectives ((adjective "purple") ))(condition (pristine ))(piled_on ((item (name "X-4292-THZ")(description "an exemplary instance of part number X-4292-THZ")(adjectives ((adjective "lime") ))(condition (pristine ))(piled_on ((item (name "L-9887-EUO")(description "an exemplary instance of part number L-9887-EUO")(adjectives ((adjective "beige") ))(condition (broken (condition (broken (condition (broken (condition (pristine ))(missing ((kind (name "B-9247-YHS")(condition (broken (condition (pristine ))(missing ((kind (name "F-4832-DKZ")(condition (pristine ))) ))))) ))))(missing ((kind (name "H-5065-MGC")(condition (pristine ))) ))))(missing ((kind (name "X-1403-GSG")(condition (pristine ))) ))))(piled_on ((item (name "T-1623-OES")(description "an exemplary instance of part number T-1623-OES")(adjectives ((adjective "deep-pink") ))(condition (pristine ))(piled_on ((item (name "X-1403-GSG")(description "an exemplary instance of part number X-1403-GSG")(adjectives ((adjective "plum") ))(condition (broken (condition (pristine ))(missing ((kind (name "D-9247-URO")(condition (pristine ))) ))))(piled_on ((item (name "D-9247-URO")(description "an exemplary instance of part number D-9247-URO")(adjectives ((adjective "malachite") ))(condition (pristine ))(piled_on ((item (name "N-0010-NQP")(description "an exemplary instance of part number N-0010-NQP")(adjectives ((adjective "fuchsia") ))(condition (broken (condition (broken (condition (pristine ))(missing ((kind (name "V-4292-XWF")(condition (broken (condition (pristine ))(missing ((kind (name "Z-9887-CAM")(condition (broken (condition (pristine ))(missing ((kind (name "D-6458-HDT")(condition (pristine ))) ))))) ))))) ))))(missing ((kind (name "R-6458-FIR")(condition (pristine ))) ))))(piled_on ((item (name "B-0010-LVN")(description "an exemplary instance of part number B-0010-LVN")(adjectives ((adjective "dodger-blue") ))(condition (broken (condition (pristine ))(missing ((kind (name "F-1623-QYU")(condition (broken (condition (broken (condition (pristine ))(missing ((kind (name "J-4292-VCD")(condition (pristine ))) ))))(missing ((kind (name "N-9887-AFK")(condition (pristine ))) ))))) ))))(piled_on ((item (name "D-1623-UOY")(description "an exemplary instance of part number D-1623-UOY")(adjectives ((adjective "pine-green") ))(condition (broken (condition (pristine ))(missing ((kind (name "H-4292-ZRH")(condition (pristine ))) ))))(piled_on ((item (name "V-4292-XWF")(description "an exemplary instance of part number V-4292-XWF")(adjectives ((adjective "floral-white") ))(condition (broken (condition (broken (condition (pristine ))(missing ((kind (name "Z-9887-CAM")(condition (broken (condition (pristine ))(missing ((kind (name "D-6458-HDT")(condition (pristine ))) ))))) ))))(missing ((kind (name "L-6678-RJJ")(condition (broken (condition (pristine ))(missing ((kind (name "P-9247-WMQ")(condition (broken (condition (pristine ))(missing ((kind (name "T-4832-BPX")(condition (pristine ))) ))))) ))))) ))))(piled_on ((item (name "H-5065-MGC")(description "an exemplary instance of part number H-5065-MGC")(adjectives ((adjective "bisque") ))(condition (pristine ))(piled_on ((item (name "V-1403-KIK")(description "an exemplary instance of part number V-1403-KIK")(adjectives ((adjective "violet") ))(condition (broken (condition (broken (condition (pristine ))(missing ((kind (name "Z-0010-PLR")(condition (pristine ))) ))))(missing ((kind (name "P-6458-JXV")(condition (broken (condition (pristine ))(missing ((kind (name "T-5065-OBE")(condition (pristine ))) ))))) ))))(piled_on ((item (name "R-1623-STW")(description "an exemplary instance of part number R-1623-STW")(adjectives ((adjective "burlywood-colored") ))(condition (pristine ))(piled_on ((item (name "R-5065-SQI")(description "an exemplary instance of part number R-5065-SQI")(adjectives ((adjective "misty-rose") ))(condition (broken (condition (broken (condition (broken (condition (pristine ))(missing ((kind (name "V-6678-XTP")(condition (broken (condition (pristine ))(missing ((kind (name "Z-9247-CWW")(condition (pristine ))) ))))) ))))(missing ((kind (name "X-9887-GPQ")(condition (pristine ))) ))))(missing ((kind (name "X-6678-TEL")(condition (pristine ))) ))))(piled_on ((item (name "X-6678-TEL")(description "an exemplary instance of part number X-6678-TEL")(adjectives ((adjective "sea-green") ))(condition (pristine ))(piled_on ((item (name "P-1623-WJC")(description "an exemplary instance of part number P-1623-WJC")(adjectives ((adjective "bronze") ))(condition (broken (condition (pristine ))(missing ((kind (name "R-4832-FFD")(condition (pristine ))) ))))(piled_on ((item (name "P-6458-JXV")(description "an exemplary instance of part number P-6458-JXV")(adjectives ((adjective "midnight-blue") ))(condition (broken (condition (pristine ))(missing ((kind (name "T-5065-OBE")(condition (pristine ))) ))))(piled_on ((item (name "B-6458-LSX")(description "an exemplary instance of part number B-6458-LSX")(adjectives ((adjective "old") ))(condition (broken (condition (broken (condition (pristine ))(missing ((kind (name "F-5065-QVG")(condition (pristine ))) ))))(missing ((kind (name "J-6678-VYN")(condition (pristine ))) ))))(piled_on ((item (name "H-1403-MDM")(description "an exemplary instance of part number H-1403-MDM")(adjectives ((adjective "rotating") ))(condition (broken (condition (pristine ))(missing ((kind (name "L-0010-RGT")(condition (pristine ))) ))))(piled_on ((item (name "H-6678-ZOR")(description "an exemplary instance of part number H-6678-ZOR")(adjectives ((adjective "cream") ))(condition (broken (condition (broken (condition (broken (condition (pristine ))(missing ((kind (name "L-9247-ERY")(condition (pristine ))) ))))(missing ((kind (name "V-1403-KIK")(condition (broken (condition (pristine ))(missing ((kind (name "Z-0010-PLR")(condition (pristine ))) ))))) ))))(missing ((kind (name "L-9887-EUO")(condition (pristine ))) ))))(piled_on ((item (name "P-4832-JUH")(description "an exemplary instance of part number P-4832-JUH")(adjectives ((adjective "tepid") ))(condition (broken (condition (broken (condition (broken (condition (pristine ))(missing ((kind (name "T-1403-OXO")(condition (pristine ))) ))))(missing ((kind (name "P-1623-WJC")(condition (pristine ))) ))))(missing ((kind (name "B-6458-LSX")(condition (broken (condition (broken (condition (pristine ))(missing ((kind (name "F-5065-QVG")(condition (pristine ))) ))))(missing ((kind (name "J-6678-VYN")(condition (pristine ))) ))))) ))))(piled_on ((item (name "R-4832-FFD")(description "an exemplary instance of part number R-4832-FFD")(adjectives ((adjective "powder-blue") ))(condition (pristine ))(piled_on ((item (name "N-9247-ACU")(description "an exemplary instance of part number N-9247-ACU")(adjectives ((adjective "cobalt") ))(condition (pristine ))(piled_on ((item (name "N-6458-NNZ")(description "an exemplary instance of part number N-6458-NNZ")(adjectives ((adjective "burlywood-colored") ))(condition (pristine ))(piled_on ((item (name "Z-6458-PID")(description "an exemplary instance of part number Z-6458-PID")(adjectives ((adjective "foreign") ))(condition (broken (condition (broken (condition (broken (condition (broken (condition (broken (condition (pristine ))(missing ((kind (name "H-6678-ZOR")(condition (broken (condition (pristine ))(missing ((kind (name "L-9247-ERY")(condition (pristine ))) ))))) ))))(missing ((kind (name "X-0010-TBV")(condition (pristine ))) ))))(missing ((kind (name "N-6458-NNZ")(condition (pristine ))) ))))(missing ((kind (name "D-4832-HAF")(condition (pristine ))) ))))(missing ((kind (name "H-1403-MDM")(condition (broken (condition (pristine ))(missing ((kind (name "L-0010-RGT")(condition (pristine ))) ))))) ))))(piled_on ((item (name "X-9887-GPQ")(description "an exemplary instance of part number X-9887-GPQ")(adjectives ((adjective "discounted") ))(condition (pristine ))(piled_on ((item (name "T-4292-BMJ")(description "an exemplary instance of part number T-4292-BMJ")(adjectives ((adjective "floating") ))(condition (pristine ))(piled_on ((item (name "D-4832-HAF")(description "an exemplary instance of part number D-4832-HAF")(adjectives ((adjective "pine-green") ))(condition (pristine ))(piled_on ((item (name "D-5065-ULK")(description "an exemplary instance of part number D-5065-ULK")(adjectives ((adjective "hot-pink") ))(condition (broken (condition (pristine ))(missing ((kind (name "R-5065-SQI")(condition (broken (condition (pristine ))(missing ((kind (name "V-6678-XTP")(condition (broken (condition (pristine ))(missing ((kind (name "Z-9247-CWW")(condition (pristine ))) ))))) ))))) ))))(piled_on ((item (name "V-9887-KFU")(description "an exemplary instance of part number V-9887-KFU")(adjectives ((adjective "green") ))(condition (broken (condition (pristine ))(missing ((kind (name "Z-6458-PID")(condition (pristine ))) ))))(piled_on ((item (name "F-4292-DHL")(description "an exemplary instance of part number F-4292-DHL")(adjectives ((adjective "violet-red") ))(condition (broken (condition (pristine ))(missing ((kind (name "J-9887-IKS")(condition (pristine ))) ))))(piled_on ((item (name "progress bar")(description "a visual indication of how much data has yet to be transfered")(adjectives )(condition (pristine ))(piled_on ((item (name "B-1623-YEE")(description "an exemplary instance of part number B-1623-YEE")(adjectives ((adjective "tepid") ))(condition (pristine ))(piled_on ((item (name "X-0010-TBV")(description "an exemplary instance of part number X-0010-TBV")(adjectives ((adjective "indigo") ))(condition (pristine ))(piled_on ((item (name "N-1623-AYG")(description "an exemplary instance of part number N-1623-AYG")(adjectives )(condition (pristine ))(piled_on )) ))) ))) ))) ))) ))) ))) ))) ))) ))) ))) ))) ))) ))) ))) ))) ))) ))) ))) ))) ))) ))) ))) ))) ))) ))) ))) ))) ))) ))) ))) ))) ))) ))) ))) ))) ))) ))) ))) ))) ))) ))) ))) ))) ))) ))) ))) ))) ))) ))) ))) ))) ))) ))) ))) ))))))
#<<END
get cerise V-5065-KLY
incinerate cerise V-5065-KLY
get foreign J-5065-IQW
incinerate foreign J-5065-IQW
get floating X-5065-GVU
incinerate floating X-5065-GVU
get chartreuse B-6678-LYD
incinerate chartreuse B-6678-LYD
get lavender N-1403-AIY
incinerate lavender N-1403-AIY
get bondi-blue R-0010-FLH
incinerate bondi-blue R-0010-FLH
get old V-1623-KOO
incinerate old V-1623-KOO
get deep-sky-blue Z-1403-CDC
incinerate deep-sky-blue Z-1403-CDC
get hot-pink B-9887-YKI
incinerate hot-pink B-9887-YKI
get ultramarine P-9887-WPG
incinerate ultramarine P-9887-WPG
get fern-green F-9247-QCK
incinerate fern-green F-9247-QCK
get lime-green B-9247-YHS
incinerate lime-green B-9247-YHS
get reverse-chirality J-1403-INI
incinerate reverse-chirality J-1403-INI
get school-bus-yellow L-4292-RMX
incinerate school-bus-yellow L-4292-RMX
get yellow-green R-6458-FIR
incinerate yellow-green R-6458-FIR
get puce R-9247-SWM
incinerate puce R-9247-SWM
get carrot V-4832-XAT
incinerate carrot V-4832-XAT
get discounted H-4832-ZUV
incinerate discounted H-4832-ZUV
get hot-pink N-6678-NTF
incinerate hot-pink N-6678-NTF
get exceptional L-6678-RJJ
incinerate exceptional L-6678-RJJ
get purple F-6458-DNP
incinerate purple F-6458-DNP
get lime X-4292-THZ
incinerate lime X-4292-THZ
get beige L-9887-EUO
incinerate beige L-9887-EUO
get deep-pink T-1623-OES
incinerate deep-pink T-1623-OES
get plum X-1403-GSG
incinerate plum X-1403-GSG
get malachite D-9247-URO
incinerate malachite D-9247-URO
get fuchsia N-0010-NQP
incinerate fuchsia N-0010-NQP
get dodger-blue B-0010-LVN
incinerate dodger-blue B-0010-LVN
get pine-green D-1623-UOY
incinerate pine-green D-1623-UOY
get floral-white V-4292-XWF
incinerate floral-white V-4292-XWF
get bisque H-5065-MGC
incinerate bisque H-5065-MGC
get violet V-1403-KIK
incinerate violet V-1403-KIK
get burlywood-colored R-1623-STW
incinerate burlywood-colored R-1623-STW
get misty-rose R-5065-SQI
incinerate misty-rose R-5065-SQI
get sea-green X-6678-TEL
incinerate sea-green X-6678-TEL
get bronze P-1623-WJC
incinerate bronze P-1623-WJC
get midnight-blue P-6458-JXV
incinerate midnight-blue P-6458-JXV
get old B-6458-LSX
incinerate old B-6458-LSX
get rotating H-1403-MDM
incinerate rotating H-1403-MDM
get cream H-6678-ZOR
incinerate cream H-6678-ZOR
get tepid P-4832-JUH
incinerate tepid P-4832-JUH
get powder-blue R-4832-FFD
incinerate powder-blue R-4832-FFD
get cobalt N-9247-ACU
incinerate cobalt N-9247-ACU
get burlywood-colored N-6458-NNZ
incinerate burlywood-colored N-6458-NNZ
get foreign Z-6458-PID
incinerate foreign Z-6458-PID
get discounted X-9887-GPQ
incinerate discounted X-9887-GPQ
get floating T-4292-BMJ
incinerate floating T-4292-BMJ
get pine-green D-4832-HAF
incinerate pine-green D-4832-HAF
get hot-pink D-5065-ULK
incinerate hot-pink D-5065-ULK
get green V-9887-KFU
incinerate green V-9887-KFU
get violet-red F-4292-DHL
incinerate violet-red F-4292-DHL
get progress bar


END