#lang s-exp "../rooms.rkt"
; Start of city
6 "downloader"
(success (command (look (room (name "54th Street and Ridgewood Court")(description "You are standing at the corner of 54th Street and Ridgewood Court. From here, you can go east. ")(items ((item (name "/etc/passwd")(description "some kind of lost inode. It reads:
howie:xyzzy:Howard Curry:/home/howie
yang:U+262F:Y Yang:/home/yang
hmonk:COMEFROM:Harmonious Monk:/home/hmonk")(adjectives )(condition (pristine ))(piled_on ((item (name "note")(description "written in a familiar hand. 
It reads: Dear Self, I had to erase our memory to protect the truth. The Municipality has become more powerful than we had feared. Its Censory Engine has impeded the spread of information throughout our ranks. I've left two useful items for you here, but I had to disassemble them and scatter the pieces. Each piece may be assembled from the items at a single location. Repair the items and recover the blueprint from the Museum of Science and Industry; it will show you how to proceed. If you have trouble reading the blueprint, know that the Censory Engine blocks only your perception, not your actions. Have courage, my self, the abstraction is weak! P.S. SWITCH your GOGGLES!")(adjectives ((adjective "self-addressed") ))(condition (pristine ))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         (piled_on ((item (name "downloader")(description "(according to the label) fully compatible with third generation municipal robots")(adjectives )(condition (broken (condition (pristine ))(missing ((kind (name "USB cable")(condition (pristine ))) ((kind (name "display")(condition (pristine ))) ((kind (name "jumper shunt")(condition (pristine ))) ((kind (name "progress bar")(condition (pristine ))) ((kind (name "power cord")(condition (pristine ))) ))))))))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          (piled_on ((item (name "uploader")(description "used to update firmware on municipal robots. A label reads, Warning: use of this device will void your robot's warranty")(adjectives )(condition (broken (condition (pristine ))(missing ((kind (name "MOSFET")(condition (pristine ))) ((kind (name "status LED")(condition (pristine ))) ((kind (name "RS232 adapter")(condition (pristine ))) ((kind (name "EPROM burner")(condition (pristine ))) ((kind (name "battery")(condition (pristine ))) ))))))))(piled_on )) ))) ))) ))) ))))))
#<<END
END
